environments:
  docker_images:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
    pipelines:
    - python-notebook
    - r-notebook
    - slurm-notebook
    - python-cuda-notebook
    - gpu-notebook
    - dgx1-notebook
    - datascience-notebook
    - chemistry-notebook
    - fenics-notebook
    - qsharp-notebook
    - statistics-notebook
    - tomography-notebook
    - hpc-notebook
    - hpc-ocean-notebook
    - ocean-notebook
    - geo-notebook
    - bio-notebook
    - bio-bigdata-notebook
    - bio-bsa-notebook
    - sme-notebook
    - base-notebook
format_version: 10
pipelines:
  base-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: &id001
      ucphhpc_images:
        branch: master
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: base-notebook
      ARGS: ""
    template: notebook_image
  bio-bigdata-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bigdata-notebook
      ARGS: ""
    template: notebook_image
  bio-bsa-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bsa-notebook
      ARGS: ""
    template: notebook_image
  bio-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: bio-notebook
      ARGS: ""
    template: notebook_image
  chemistry-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: chemistry-notebook
      ARGS: ""
    template: notebook_image
  datascience-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: datascience-notebook
      ARGS: ""
    template: notebook_image
  dgx1-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: dgx1-notebook
      ARGS: ""
    template: notebook_image
  fenics-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: fenics-notebook
      ARGS: ""
    template: notebook_image
  geo-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: geo-notebook
      ARGS: ""
    template: notebook_image
  gpu-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: gpu-notebook
      ARGS: ""
    template: notebook_image
  hpc-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: hpc-notebook
      ARGS: ""
    template: notebook_image
  hpc-notebook-20.02.7:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: 20.02.7
      NOTEBOOK: hpc-notebook
      PARENT_NOTEBOOK: slurm-notebook:20.02.7
      ARGS: ""
    template: notebook_image
  hpc-notebook-21.08.0:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-notebook
      PARENT_NOTEBOOK: slurm-notebook:21.08.0
      ARGS: ""
    template: notebook_image
  hpc-ocean-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: hpc-ocean-notebook
      ARGS: ""
    template: notebook_image
  ocean-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: ocean-notebook
      ARGS: ""
    template: notebook_image
  python-cuda-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: python-cuda-notebook
      ARGS: ""
    template: notebook_image
  python-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: python-notebook
      ARGS: ""
    template: notebook_image
  qsharp-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: qsharp-notebook
      ARGS: ""
    template: notebook_image
  r-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: r-notebook
      ARGS: ""
    template: notebook_image
  slurm-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: slurm-notebook
      ARGS: ""
    template: notebook_image
  slurm-notebook-20.02.7:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: 20.02.7
      NOTEBOOK: slurm-notebook
      ARGS: "--build-arg SLURM_VERSION=20.02.7 --build-arg SLURM_DOWNLOAD_MD5=e47e68692354f03db2999ec84fe3f735"
    template: notebook_image
  slurm-notebook-21.08.0:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: slurm-notebook
      ARGS: "--build-arg SLURM_VERSION=21.08.0 --build-arg SLURM_DOWNLOAD_MD5=a5bf9ab2733f520cd8229513431ad787"
    template: notebook_image
  sme-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: sme-notebook
      ARGS: ""
    template: notebook_image
  statistics-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: statistics-notebook
      ARGS: ""
    template: notebook_image
  tomography-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: tomography-notebook
      ARGS: ""
    template: notebook_image
