environments:
  notebook_image:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
    pipelines:
    - base-notebook-latest
    - python-notebook-latest
    - r-notebook-latest
    - slurm-notebook-20.02.7
    - slurm-notebook-21.08.0
    - python-cuda-notebook-latest
    - gpu-notebook-latest
    - dgx1-notebook-latest
    - datascience-notebook-latest
    - chemistry-notebook-latest
    - fenics-notebook-latest
    - qsharp-notebook-latest
    - hpc-gpu-notebook-latest
    - hpc-notebook-latest
    - hpc-notebook-20.02.7
    - hpc-notebook-21.08.0
    - hpc-ocean-notebook-latest
    - hpc-ocean-notebook-20.02.7
    - hpc-ocean-notebook-21.08.0
    - ocean-notebook-latest
    - geo-notebook-latest
    - bio-notebook-latest
    - bio-bigdata-notebook-latest
    - bio-bsa-notebook-latest
    - sme-notebook-latest
    - jwst-notebook-latest
format_version: 10
pipelines:
  base-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: &id001
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: master
        destination: nbi-jupyter-docker-stacks
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: base-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  bio-bigdata-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bigdata-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  bio-bsa-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bsa-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  bio-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  chemistry-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: chemistry-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  datascience-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: datascience-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  dgx1-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: dgx1-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  fenics-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: fenics-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  geo-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: geo-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  gpu-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: gpu-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-gpu-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: hpc-gpu-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-notebook-20.02.7:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 20.02.7
      NOTEBOOK: hpc-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-notebook-21.08.0:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: hpc-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-ocean-notebook-20.02.7:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 20.02.7
      NOTEBOOK: hpc-ocean-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-ocean-notebook-21.08.0:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-ocean-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-ocean-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: hpc-ocean-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  jwst-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: jwst-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  ocean-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: ocean-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  python-cuda-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: python-cuda-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  python-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: python-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  qsharp-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: qsharp-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  r-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: r-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  slurm-notebook-20.02.7:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 20.02.7
      NOTEBOOK: slurm-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  slurm-notebook-21.08.0:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: slurm-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  sme-notebook-latest:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: sme-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
