format_version: 10
pipelines:
  nbi_jupyter_docker_stacks:
    group: ucphhpc
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      repo_nbi_jupyter_docker_stacks:
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build-all
                command: make
                run_if: passed
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
         test:
          timeout: 0
          tasks:
          - exec:
              arguments:
              - test-all
              command: make
              run_if: passed
