environments:
  docker_images:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
    pipelines:
    - base_notebook
    - python_notebook
    - r_notebook
    - slurm_notebook
    - python_cuda_notebook
    - gpu_notebook
    - dgx1_notebook
    - datascience_notebook
    - chemistry_notebook
    - fenics_notebook
    - qsharp_notebook
    - hpc_gpu_notebook
    - hpc_notebook
    - hpc_ocean_notebook
    - ocean_notebook
    - geo_notebook
    - bio_notebook
    - bio_bigdata_notebook
    - bio_bsa_notebook
    - sme-notebook
    - jwst_notebook
format_version: 10
pipelines:
  base-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: &id001
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: master
        destination: nbi-jupyter-docker-stacks
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: base-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: base-notebook
      TEST_DIRECTORY: base-notebook
    template: notebook_image
  bio-bigdata-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bigdata-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: bio-bigdata-notebook
      TEST_DIRECTORY: bio-bigdata-notebook
    template: notebook_image
  bio-bsa-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bsa-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: bio-bsa-notebook
      TEST_DIRECTORY: bio-bsa-notebook
    template: notebook_image
  bio-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: bio-notebook
      TEST_DIRECTORY: bio-notebook
    template: notebook_image
  chemistry-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: chemistry-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: chemistry-notebook
      TEST_DIRECTORY: chemistry-notebook
    template: notebook_image
  datascience-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: datascience-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: datascience-notebook
      TEST_DIRECTORY: datascience-notebook
    template: notebook_image
  dgx1-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: dgx1-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: dgx1-notebook
      TEST_DIRECTORY: dgx1-notebook
    template: notebook_image
  fenics-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: fenics-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: fenics-notebook
      TEST_DIRECTORY: fenics-notebook
    template: notebook_image
  geo-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: geo-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: geo-notebook
      TEST_DIRECTORY: geo-notebook
    template: notebook_image
  gpu-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: gpu-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: gpu-notebook
      TEST_DIRECTORY: gpu-notebook
    template: notebook_image
  hpc-gpu-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: hpc-gpu-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: hpc-gpu-notebook
      TEST_DIRECTORY: hpc-gpu-notebook
    template: notebook_image
  hpc-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: hpc-notebook
      TEST_DIRECTORY: hpc-notebook
    template: notebook_image
  hpc-ocean-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-ocean-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: hpc-ocean-notebook
      TEST_DIRECTORY: hpc-ocean-notebook
    template: notebook_image
  jwst-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: jwst-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: jwst-notebook
      TEST_DIRECTORY: jwst-notebook
    template: notebook_image
  ocean-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: ocean-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: ocean-notebook
      TEST_DIRECTORY: ocean-notebook
    template: notebook_image
  python-cuda-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: python-cuda-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: python-cuda-notebook
      TEST_DIRECTORY: python-cuda-notebook
    template: notebook_image
  python-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: python-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: python-notebook
      TEST_DIRECTORY: python-notebook
    template: notebook_image
  qsharp-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: qsharp-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: qsharp-notebook
      TEST_DIRECTORY: qsharp-notebook
    template: notebook_image
  r-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: r-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: r-notebook
      TEST_DIRECTORY: r-notebook
    template: notebook_image
  slurm-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: slurm-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: slurm-notebook
      TEST_DIRECTORY: slurm-notebook
    template: notebook_image
  sme-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: sme-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: sme-notebook
      TEST_DIRECTORY: sme-notebook
    template: notebook_image
