environments:
  docker_images:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
      RELEASE: latest
    pipelines:
    - python-notebook
    - r-notebook
    - slurm-notebook
    - python-cuda-notebook
    - gpu-notebook
    - dgx1-notebook
    - datascience-notebook
    - chemistry-notebook
    - fenics-notebook
    - qsharp-notebook
    - statistics-notebook
    - tomography-notebook
    - hpc-notebook
    - hpc-ocean-notebook
    - ocean-notebook
    - geo-notebook
    - bio-notebook
    - bio-bigdata-notebook
    - bio-bsa-notebook
    - sme-notebook
    - base-notebook
format_version: 10
pipelines:
  base-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: &id001
      ucphhpc_images:
        branch: master
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
    parameters:
      NOTEBOOK: base-notebook
    template: notebook_image
  bio-bigdata-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: bio-bigdata-notebook
    template: notebook_image
  bio-bsa-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: bio-bsa-notebook
    template: notebook_image
  bio-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: bio-notebook
    template: notebook_image
  chemistry-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: chemistry-notebook
    template: notebook_image
  datascience-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: datascience-notebook
    template: notebook_image
  dgx1-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: dgx1-notebook
    template: notebook_image
  fenics-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: fenics-notebook
    template: notebook_image
  geo-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: geo-notebook
    template: notebook_image
  gpu-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: gpu-notebook
    template: notebook_image
  hpc-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: hpc-notebook
    template: notebook_image
  hpc-ocean-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: hpc-ocean-notebook
    template: notebook_image
  ocean-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: ocean-notebook
    template: notebook_image
  python-cuda-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: python-cuda-notebook
    template: notebook_image
  python-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: python-notebook
    template: notebook_image
  qsharp-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: qsharp-notebook
    template: notebook_image
  r-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: r-notebook
    template: notebook_image
  slurm-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: slurm-notebook
    template: notebook_image
  sme-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: sme-notebook
    template: notebook_image
  statistics-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: statistics-notebook
    template: notebook_image
  tomography-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      NOTEBOOK: tomography-notebook
    template: notebook_image
