format_version: 10
pipelines:
  docker_images:
    group: ucphhpc
    parameters:
      NOTEBOOK: base-notebook
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      nbi_images:
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
        branch: master
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            build:
              elastic_profile_id: "docker"
              timeout: 0
              tasks:
                - exec:
                    command: make
                    arguments:
                      - build/#{NOTEBOOK}
                    run_if: passed
      - test:
          fetch_materials: true
          keep_artifacts: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            test:
              elastic_profile_id: "docker"
              timeout: 0
              tasks:
                - exec:
                    command: make
                    arguments:
                      - test/#{NOTEBOOK}

      - push:
          fetch_materials: true
          keep_artifacts: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            push:
              elastic_profile_id: "docker"
              timeout: 0
              tasks:
                - exec:
                    command: docker
                    arguments:
                      - login
                      - -u $DOCKERHUB_USERNAME
                      - -p $DOCKERHUB_PASSWORD
                - exec:
                    command: make
                    arguments:
                      - push/#{NOTEBOOK}
