environments:
  docker_images:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
    pipelines:
    - base_notebook
    - python_notebook
    - r_notebook
    - slurm_notebook
    - python_cuda_notebook
    - gpu_notebook
    - dgx1_notebook
    - datascience_notebook
    - chemistry_notebook
    - fenics_notebook
    - qsharp_notebook
    - hpc_notebook
    - hpc_ocean_notebook
    - ocean_notebook
    - geo_notebook
    - bio_notebook
    - bio_bigdata_notebook
    - bio_bsa_notebook
    - sme-notebook
    - jwst_notebook
format_version: 10
pipelines:
  base_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: &id001
      ucphhpc_images:
        branch: master
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: base_notebook
      TAG: latest
    template: notebook_image
  bio_bigdata_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: bio_bigdata_notebook
      TAG: latest
    template: notebook_image
  bio_bsa_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: bio_bsa_notebook
      TAG: latest
    template: notebook_image
  bio_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: bio_notebook
      TAG: latest
    template: notebook_image
  chemistry_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: chemistry_notebook
      TAG: latest
    template: notebook_image
  datascience_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: datascience_notebook
      TAG: latest
    template: notebook_image
  dgx1_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: dgx1_notebook
      TAG: latest
    template: notebook_image
  fenics_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: fenics_notebook
      TAG: latest
    template: notebook_image
  geo_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: geo_notebook
      TAG: latest
    template: notebook_image
  gpu_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: gpu_notebook
      TAG: latest
    template: notebook_image
  hpc_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: hpc_notebook
      TAG: 21.08.0
    template: notebook_image
  hpc_ocean_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: hpc_ocean_notebook
      TAG: 21.08.0
    template: notebook_image
  jwst_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: jwst_notebook
      TAG: latest
    template: notebook_image
  ocean_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: ocean_notebook
      TAG: latest
    template: notebook_image
  python_cuda_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: python_cuda_notebook
      TAG: latest
    template: notebook_image
  python_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: python_notebook
      TAG: latest
    template: notebook_image
  qsharp_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: qsharp_notebook
      TAG: latest
    template: notebook_image
  r_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: r_notebook
      TAG: latest
    template: notebook_image
  slurm_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: slurm_notebook
      TAG: 21.08.0
    template: notebook_image
  sme-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      NOTEBOOK: sme-notebook
      TAG: latest
    template: notebook_image
