environments:
  docker_images:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
    pipelines:
    - base_notebook
    - python_notebook
    - r_notebook
    - slurm_notebook
    - python_cuda_notebook
    - gpu_notebook
    - dgx1_notebook
    - datascience_notebook
    - chemistry_notebook
    - fenics_notebook
    - qsharp_notebook
    - hpc_gpu_notebook
    - hpc_notebook
    - hpc_ocean_notebook
    - ocean_notebook
    - geo_notebook
    - bio_notebook
    - bio_bigdata_notebook
    - bio_bsa_notebook
    - sme-notebook
    - jwst_notebook
format_version: 10
pipelines:
  base_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: &id001
      ucphhpc_images:
        branch: master
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: base-notebook
    template: notebook_image
  bio_bigdata_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bigdata-notebook
    template: notebook_image
  bio_bsa_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bsa-notebook
    template: notebook_image
  bio_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: bio-notebook
    template: notebook_image
  chemistry_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: chemistry-notebook
    template: notebook_image
  datascience_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: datascience-notebook
    template: notebook_image
  dgx1_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: dgx1-notebook
    template: notebook_image
  fenics_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: fenics-notebook
    template: notebook_image
  geo_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: geo-notebook
    template: notebook_image
  gpu_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: gpu-notebook
    template: notebook_image
  hpc_gpu_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: hpc-gpu-notebook
    template: notebook_image
  hpc_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-notebook
    template: notebook_image
  hpc_ocean_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-ocean-notebook
    template: notebook_image
  jwst_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: jwst-notebook
    template: notebook_image
  ocean_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: ocean-notebook
    template: notebook_image
  python_cuda_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: python-cuda-notebook
    template: notebook_image
  python_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: python-notebook
    template: notebook_image
  qsharp_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: qsharp-notebook
    template: notebook_image
  r_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: r-notebook
    template: notebook_image
  slurm_notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: slurm-notebook
    template: notebook_image
  sme-notebook:
    display_order: -1
    group: ucphhpc
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: ${GO_REVISION_UCPHHPC_IMAGES}
      DEFAULT_TAG: latest
      NOTEBOOK: sme-notebook
    template: notebook_image
