format_version: 10
pipelines:
  docker_images:
    group: simple
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      nbi_images:
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
        username: munk1@live.dk
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:5Ya+5kkqYIqUywWwY7x5sA==:5I+cRzZ/WvF4S7ApDGOTQA==
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          image:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    build/#{NOTEBOOK}
                  command: make
                  run_if: passed
    - test:
        fetch_materials: true
        keep_artifacts: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          image:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    test/#{NOTEBOOK}
                  command: make
    - push:
        fetch_materials: true
        keep_artifacts: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          image:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    push/#{NOTEBOOK}
                  command: make