environments:
  docker_images:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
    pipelines:
    - base-notebook
    - python-notebook
    - r-notebook
    - slurm-notebook
    - python-cuda-notebook
    - gpu-notebook
    - dgx1-notebook
    - datascience-notebook
    - chemistry-notebook
    - fenics-notebook
    - qsharp-notebook
    - hpc-gpu-notebook
    - hpc-notebook
    - hpc-ocean-notebook
    - ocean-notebook
    - geo-notebook
    - bio-notebook
    - bio-bigdata-notebook
    - bio-bsa-notebook
    - sme-notebook
    - jwst-notebook
format_version: 10
pipelines:
  base-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: &id001
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: master
        destination: nbi-jupyter-docker-stacks
        git: https://github.com/ucphhpc/nbi-jupyter-docker-stacks.git
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: base-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  bio-bigdata-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bigdata-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  bio-bsa-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-bsa-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  bio-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: bio-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  chemistry-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: chemistry-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  datascience-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: datascience-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  dgx1-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: dgx1-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  fenics-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: fenics-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  geo-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: geo-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  gpu-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: gpu-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-gpu-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: hpc-gpu-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  hpc-ocean-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: hpc-ocean-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  jwst-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: jwst-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  ocean-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: ocean-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  python-cuda-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: python-cuda-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  python-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: python-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  qsharp-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: qsharp-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  r-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: r-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  slurm-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: 21.08.0
      NOTEBOOK: slurm-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
  sme-notebook:
    display_order: -1
    group: notebook_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials: *id001
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_UCPHHPC_IMAGES
      DEFAULT_TAG: latest
      NOTEBOOK: sme-notebook
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: nbi-jupyter-docker-stacks
      TEST_DIRECTORY: nbi-jupyter-docker-stacks
    template: notebook_image
