name: r-notebook
dependencies:
  - gxx_linux-64
  - libgfortran
  - r-base=4.3.*
  - r-boot=1.*
  - r-caret=6.*
  - r-crayon=1.*
  - r-devtools=2.*
  - r-e1071=1.*
  - r-forecast=8.*
  - r-hexbin=1.*
  - r-htmltools=0.*
  - r-htmlwidgets=1.*
  - r-irkernel=1.*
  - r-leaps=3.*
  - r-nycflights13=1.0*
  - r-pheatmap=1.0*
  - r-plyr=1.8*
  - r-randomforest=4.7*
  - r-RColorBrewer=1.*
  - r-rcurl=1.*
  - r-readr=2.*
  - r-reshape2=1.*
  - r-rjson=0.*
  - r-rmarkdown=2.*
  - r-rocr=1.*
  - r-rodbc=1.*
  - r-rsqlite=2.*
  - r-rtsne=0.*
  - r-shiny=1.*
  - r-sparklyr=1.*
  - r-tidyverse=2.*
  - r-v8=4.*
  - unixodbc=2.3.*
channels:
  - conda-forge