name: geo-notebook
dependencies:
   - arrow
   - autopep8
   - bokeh
   - bqplot
   - cartopy<=0.22.0
   - cdo
   - cftime
   - click
   - cmocean
   - colorcet
   - cython 
   - cytoolz
   - dask
   - dask-ml
   - datashader
   - distributed
   - eofs
   - esmpy
   - fastparquet
   - flake8
   - gdal
   - geoviews
   - graphviz
   - gsw
   - hvplot
   - iris
   - jedi
   - libsodium
   - lmfit
   - lz4
   - matplotlib-base<=3.8.4
   - matplotlib-inline<=0.1.6
   - msgpack-python
   - nb_conda_kernels
   - nco
   - nc-time-axis
   - netcdf4
   - nodejs
   - nomkl
   - numba
   - numcodecs
   - numpy<=1.26.4
   - palettable
   - pandas
   - pyarrow
   - panel
   - plotly
   - python-blosc
   - python-graphviz
   - rasterio<=1.3.9
   - scikit-image
   - scikit-learn
   - scipy
   - seaborn
   - statsmodels
   - toolz
   - tornado
   - xarray<=2024.3.0
   - rioxarray<=0.15.3
   - xesmf
   - zarr
   - zict
