name: bio-notebook-bio
dependencies:
  - r-phytools
  - bioconductor-deseq2
  - bioconductor-biobase
  - bioconductor-tximport
  - bioconductor-sva
  - bioconductor-preprocesscore
  - bioconductor-edaseq
  - bioconductor-msa
  - bioconductor-phyloseq
  - bioconductor-dada2
  - bioconductor-edgeR
  - bioconductor-metagenomeSeq
  - bioconductor-limma
  - bioconductor-Biostrings
  - bioconductor-biocinstaller
  - bioconductor-dada2
  - bioconductor-vsn
  - bioconductor-multtest
  - bioconductor-xcms
  - bioconductor-biocparallel
  - bioconductor-camera
  - bioconductor-pcamethods
  - bioconductor-apeglm
  - mafft
  - fasttree
channels:
  - bioconda
  - conda-forge